"""initial lys schema

Revision ID: 2146a537269c
Revises: 
Create Date: 2026-08-27 07:02:38.257605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2146a537269c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_level',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_conversation',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False, comment='Reference to user (soft FK - no constraint for microservices)'),
    sa.Column('client_id', sa.Uuid(as_uuid=False), nullable=True, comment='Optional tenant/client reference (soft FK - no constraint for microservices), stamped at creation time by consumers that scope conversations to a tenant'),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversation_client_id'), 'ai_conversation', ['client_id'], unique=False)
    op.create_index(op.f('ix_ai_conversation_purpose'), 'ai_conversation', ['purpose'], unique=False)
    op.create_index(op.f('ix_ai_conversation_user_id'), 'ai_conversation', ['user_id'], unique=False)
    op.create_table('client_request_status',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_request_type',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emailing_status',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emailing_type',
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('template', sa.String(), nullable=False),
    sa.Column('context_description', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_import_status',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_import_type',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gender',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_status',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_document_type',
    sa.Column('requires_acceptance', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Whether this type gates access (its current version must be accepted)'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('license_application',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('license_billing_mode',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('license_commitment',
    sa.Column('duration_months', sa.Integer(), nullable=False, comment='How long the client is bound, in months (0 = no commitment)'),
    sa.Column('renewal_months', sa.Integer(), nullable=False, comment='Months the commitment is renewed for at term (0 = no renewal)'),
    sa.Column('notice_months', sa.Integer(), nullable=False, comment='Months of notice required before the term (0 = until the term)'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('license_currency',
    sa.Column('minor_unit', sa.Integer(), nullable=False, comment='Number of decimal places of the currency (2 for EUR, 0 for JPY)'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('license_discount_grant',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('license_discount_unit',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('license_price_period',
    sa.Column('interval_months', sa.Integer(), nullable=False, comment='Number of months in one billing period'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('license_rule',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log',
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_attempt_status',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_severity',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('one_time_token_status',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('one_time_token_type',
    sa.Column('duration', sa.Integer(), nullable=False, comment='Token validity duration in minutes'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('app_name', sa.String(), nullable=True, comment='Name of the application/microservice that provides this role'),
    sa.Column('supervisor_only', sa.Boolean(), nullable=False, comment='If True, this role can only be assigned to supervisors, not client users'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stored_file_type',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_audit_log_type',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_status',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webservice_public_type',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_message',
    sa.Column('conversation_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_call_id', sa.String(length=100), nullable=True),
    sa.Column('tool_result', sa.JSON(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_message_conversation_id'), 'ai_message', ['conversation_id'], unique=False)
    op.create_table('emailing',
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('status_id', sa.String(), nullable=False),
    sa.Column('type_id', sa.String(), nullable=False),
    sa.Column('language_id', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['emailing_status.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['emailing_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emailing_type_role',
    sa.Column('emailing_type_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emailing_type_id'], ['emailing_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('emailing_type_id', 'role_id')
    )
    op.create_table('job',
    sa.Column('status_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['job_status.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_document_version',
    sa.Column('type_id', sa.String(), nullable=False),
    sa.Column('language_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('markdown_hash', sa.String(length=64), nullable=False),
    sa.Column('pdf_hash', sa.String(length=64), nullable=False),
    sa.Column('object_key', sa.String(), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['type_id'], ['legal_document_type.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_id', 'language_id', 'markdown_hash', name='uq_legal_version_source'),
    sa.UniqueConstraint('type_id', 'language_id', 'version_number', name='uq_legal_version_number')
    )
    op.create_index('ix_legal_version_current', 'legal_document_version', ['type_id', 'language_id', 'effective_date'], unique=False)
    op.create_table('license_discount',
    sa.Column('value', sa.Integer(), nullable=False, comment="How much is taken off the price, read in the discount's unit"),
    sa.Column('unit_id', sa.String(), nullable=False),
    sa.Column('grant_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['grant_id'], ['license_discount_grant.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['license_discount_unit.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_license_discount_grant_id'), 'license_discount', ['grant_id'], unique=False)
    op.create_index(op.f('ix_license_discount_unit_id'), 'license_discount', ['unit_id'], unique=False)
    op.create_table('notification_type',
    sa.Column('severity_id', sa.String(), server_default='INFO', nullable=False, comment='FK to notification_severity (INFO / SUCCESS / WARNING / ERROR)'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['severity_id'], ['notification_severity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_type_severity_id'), 'notification_type', ['severity_id'], unique=False)
    op.create_table('role_webservice',
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('webservice_id', sa.String(), nullable=False, comment='Webservice ID (string, not FK - may reference external webservices)'),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_webservice_role_id'), 'role_webservice', ['role_id'], unique=False)
    op.create_table('stored_file',
    sa.Column('client_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('type_id', sa.String(), nullable=False),
    sa.Column('object_key', sa.String(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp. When set, the S3 bytes are purged but the row is kept as a tombstone (content hash for dedup, plus audit). Still matched by the content-hash idempotency lookup; no global read filter is applied, so callers serving or listing live files must exclude it.'),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['stored_file_type.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stored_file_client_content_hash', 'stored_file', ['client_id', 'content_hash'], unique=False)
    op.create_table('user',
    sa.Column('client_id', sa.Uuid(as_uuid=False), nullable=True, comment='Client organization (null for supervisors)'),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_super_user', sa.Boolean(), nullable=False),
    sa.Column('status_id', sa.String(), nullable=False),
    sa.Column('language_id', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['user_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webservice',
    sa.Column('public_type_id', sa.String(), nullable=True, comment='Type of public access allowed (None = private webservice)'),
    sa.Column('is_licenced', sa.Boolean(), nullable=False, comment='Defined if an active licence is mandatory to call the webservice'),
    sa.Column('app_name', sa.String(), nullable=True, comment='Name of the application/microservice that provides this webservice'),
    sa.Column('operation_type', sa.String(length=20), nullable=True, comment='GraphQL operation type (query or mutation)'),
    sa.Column('ai_tool', sa.JSON(), nullable=True, comment='AI tool definition for LLM function calling'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['public_type_id'], ['webservice_public_type.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_conversation_summary',
    sa.Column('conversation_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('through_message_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['through_message_id'], ['ai_message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversation_summary_conversation_id'), 'ai_conversation_summary', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_conversation_summary_through_message_id'), 'ai_conversation_summary', ['through_message_id'], unique=False)
    op.create_table('ai_message_feedback',
    sa.Column('message_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False, comment='Reference to user (soft FK - no constraint for microservices)'),
    sa.Column('rating', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['ai_message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_message_feedback_message_id'), 'ai_message_feedback', ['message_id'], unique=True)
    op.create_index(op.f('ix_ai_message_feedback_user_id'), 'ai_message_feedback', ['user_id'], unique=False)
    op.create_table('client',
    sa.Column('provider_customer_id', sa.String(length=255), nullable=True, comment='Payment provider customer ID (Mollie: cst_xxx)'),
    sa.Column('owner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_provider_customer_id'), 'client', ['provider_customer_id'], unique=True)
    op.create_table('client_user_role',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cron_job_execution',
    sa.Column('cron', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_import',
    sa.Column('client_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('stored_file_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('type_id', sa.String(), nullable=False),
    sa.Column('status_id', sa.String(), nullable=False),
    sa.Column('total_rows', sa.BigInteger(), nullable=True),
    sa.Column('processed_rows', sa.BigInteger(), nullable=True),
    sa.Column('success_rows', sa.BigInteger(), nullable=True),
    sa.Column('error_rows', sa.BigInteger(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['file_import_status.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stored_file_id'], ['stored_file.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['type_id'], ['file_import_type.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_document_acceptance',
    sa.Column('version_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('accepted_by_email', sa.String(), nullable=False),
    sa.Column('accepted_by_name', sa.String(), nullable=True),
    sa.Column('acceptance_context', sa.JSON(), nullable=True),
    sa.Column('retention_anchor_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['legal_document_version.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'version_id', name='uq_legal_acceptance_user_version')
    )
    op.create_index('ix_legal_acceptance_email', 'legal_document_acceptance', ['accepted_by_email'], unique=False)
    op.create_index('ix_legal_acceptance_retention', 'legal_document_acceptance', ['retention_anchor_date'], unique=False)
    op.create_index('ix_legal_acceptance_user', 'legal_document_acceptance', ['user_id'], unique=False)
    op.create_index('ix_legal_acceptance_version', 'legal_document_acceptance', ['version_id'], unique=False)
    op.create_table('migration_job_execution',
    sa.Column('cron', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_batch',
    sa.Column('organization_data', sa.JSON(), nullable=True, comment='Organization scoping data (e.g., client_ids for multi-tenant filtering)'),
    sa.Column('type_id', sa.String(), nullable=False, comment='FK to notification_type'),
    sa.Column('triggered_by_user_id', sa.Uuid(as_uuid=False), nullable=True, comment='User who triggered the notification'),
    sa.Column('data', sa.JSON(), nullable=True, comment='Event data for frontend formatting (e.g., order_id, user_name)'),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['type_id'], ['notification_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_batch_triggered_by_user_id'), 'notification_batch', ['triggered_by_user_id'], unique=False)
    op.create_index(op.f('ix_notification_batch_type_id'), 'notification_batch', ['type_id'], unique=False)
    op.create_table('notification_type_role',
    sa.Column('notification_type_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_type_id'], ['notification_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_type_id', 'role_id')
    )
    op.create_table('user_audit_log',
    sa.Column('target_user_id', sa.Uuid(as_uuid=False), nullable=False, comment='User being observed or acted upon'),
    sa.Column('author_user_id', sa.Uuid(as_uuid=False), nullable=False, comment='User who created this log entry'),
    sa.Column('log_type_id', sa.String(), nullable=False, comment='Type of log: STATUS_CHANGE, ANONYMIZATION, or OBSERVATION'),
    sa.Column('message', sa.Text(), nullable=False, comment='Log message or observation (supports up to 1000 words)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (only for OBSERVATION type)'),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['log_type_id'], ['user_audit_log_type.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_email_address',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_validation_request_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_emailing',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('emailing_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['emailing_id'], ['emailing.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_event_preference',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False, comment='User who owns this preference'),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment='Event type key (e.g., FINANCIAL_IMPORT_COMPLETED)'),
    sa.Column('channel', sa.String(length=20), nullable=False, comment='Channel type: email or notification'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether this channel is enabled for this event'),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_type', 'channel', name='uq_user_event_preference_user_event_channel')
    )
    op.create_index(op.f('ix_user_event_preference_event_type'), 'user_event_preference', ['event_type'], unique=False)
    op.create_index(op.f('ix_user_event_preference_user_id'), 'user_event_preference', ['user_id'], unique=False)
    op.create_table('user_login_attempt',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('status_id', sa.String(), nullable=False),
    sa.Column('attempt_count', sa.SmallInteger(), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['login_attempt_status.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_one_time_token',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when token was used'),
    sa.Column('status_id', sa.String(), nullable=False),
    sa.Column('type_id', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['one_time_token_status.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['one_time_token_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_private_data',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False, comment='One-to-one relationship with User'),
    sa.Column('first_name', sa.String(), nullable=True, comment="User's first name"),
    sa.Column('last_name', sa.String(), nullable=True, comment="User's last name"),
    sa.Column('gender_id', sa.String(), nullable=True, comment="User's gender"),
    sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when private data was anonymized (GDPR right to be forgotten)'),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gender_id'], ['gender.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_refresh_token',
    sa.Column('once_expire_at', sa.DateTime(timezone=True), nullable=True, comment='define when the token will be expired'),
    sa.Column('connection_expire_at', sa.DateTime(timezone=True), nullable=False, comment='define when the connection will be expired'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='define when the token has been revoked'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='define the last time when the token has been used'),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('role_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE')
    )
    op.create_table('user_sso_link',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False, comment='User reference'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='SSO provider identifier (e.g. microsoft, google)'),
    sa.Column('external_user_id', sa.String(length=255), nullable=False, comment='User ID from the SSO provider (OID for Microsoft)'),
    sa.Column('external_email', sa.String(length=255), nullable=False, comment='Email address from the SSO provider'),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the SSO link was created'),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_user_id', name='uq_user_sso_link_provider_external_id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_sso_link_user_provider')
    )
    op.create_table('webservice_access_level',
    sa.Column('webservice_id', sa.String(), nullable=True),
    sa.Column('access_level_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['access_level_id'], ['access_level.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webservice_id'], ['webservice.id'], ondelete='CASCADE')
    )
    op.create_table('client_request',
    sa.Column('type_id', sa.String(), nullable=False),
    sa.Column('status_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('reason_code', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['client_request_status.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['type_id'], ['client_request_type.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_client_request_client_status', 'client_request', ['client_id', 'status_id'], unique=False)
    op.create_index('ix_client_request_processed', 'client_request', ['processed_at'], unique=False)
    op.create_index('ix_client_request_status_type', 'client_request', ['status_id', 'type_id'], unique=False)
    op.create_index('ix_client_request_user', 'client_request', ['user_id'], unique=False)
    op.create_table('license_plan',
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['license_application.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_license_plan_app_id'), 'license_plan', ['app_id'], unique=False)
    op.create_index(op.f('ix_license_plan_client_id'), 'license_plan', ['client_id'], unique=False)
    op.create_table('notification',
    sa.Column('batch_id', sa.Uuid(as_uuid=False), nullable=False, comment='FK to notification_batch'),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False, comment='Recipient user'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='Whether the notification has been read'),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['notification_batch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_batch_id'), 'notification', ['batch_id'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('license_plan_version',
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['license_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'version', name='uq_license_plan_version')
    )
    op.create_index(op.f('ix_license_plan_version_plan_id'), 'license_plan_version', ['plan_id'], unique=False)
    op.create_table('license_plan_version_price',
    sa.Column('plan_version_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('period_id', sa.String(), nullable=False),
    sa.Column('currency_id', sa.String(), nullable=False),
    sa.Column('commitment_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False, comment='Price in currency minor units for one billing period'),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['commitment_id'], ['license_commitment.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id'], ['license_currency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['period_id'], ['license_price_period.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_version_id'], ['license_plan_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_version_id', 'period_id', 'currency_id', 'commitment_id', name='uq_license_plan_version_price')
    )
    op.create_index(op.f('ix_license_plan_version_price_commitment_id'), 'license_plan_version_price', ['commitment_id'], unique=False)
    op.create_index(op.f('ix_license_plan_version_price_currency_id'), 'license_plan_version_price', ['currency_id'], unique=False)
    op.create_index(op.f('ix_license_plan_version_price_period_id'), 'license_plan_version_price', ['period_id'], unique=False)
    op.create_index(op.f('ix_license_plan_version_price_plan_version_id'), 'license_plan_version_price', ['plan_version_id'], unique=False)
    op.create_table('license_plan_version_rule',
    sa.Column('plan_version_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_version_id'], ['license_plan_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['license_rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_version_id', 'rule_id', name='uq_license_plan_version_rule')
    )
    op.create_index(op.f('ix_license_plan_version_rule_plan_version_id'), 'license_plan_version_rule', ['plan_version_id'], unique=False)
    op.create_index(op.f('ix_license_plan_version_rule_rule_id'), 'license_plan_version_rule', ['rule_id'], unique=False)
    op.create_table('subscription',
    sa.Column('client_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('plan_version_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('plan_version_price_id', sa.Uuid(as_uuid=False), nullable=True, comment='Price subscribed to; NULL on free subscriptions'),
    sa.Column('billing_mode_id', sa.String(), nullable=False),
    sa.Column('amount_due', sa.Integer(), nullable=True, comment="Amount actually owed per period, in the price's minor units; NULL when free"),
    sa.Column('receipt', sa.JSON(), nullable=True, comment='Snapshot of the commercial terms agreed to: plan, price, discount, commitment'),
    sa.Column('provider_subscription_id', sa.String(length=255), nullable=True, comment='Payment provider subscription ID (Mollie: sub_xxx)'),
    sa.Column('pending_plan_version_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True, comment='Start of current billing period'),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True, comment='End of current billing period'),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True, comment='Date when subscription was canceled (takes effect at period end)'),
    sa.Column('commitment_end_date', sa.DateTime(timezone=True), nullable=True, comment='End of the contractual commitment; NULL when not committed'),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['billing_mode_id'], ['license_billing_mode.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pending_plan_version_id'], ['license_plan_version.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_version_id'], ['license_plan_version.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_version_price_id'], ['license_plan_version_price.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_billing_mode_id'), 'subscription', ['billing_mode_id'], unique=False)
    op.create_index(op.f('ix_subscription_client_id'), 'subscription', ['client_id'], unique=True)
    op.create_index(op.f('ix_subscription_commitment_end_date'), 'subscription', ['commitment_end_date'], unique=False)
    op.create_index(op.f('ix_subscription_plan_version_id'), 'subscription', ['plan_version_id'], unique=False)
    op.create_index(op.f('ix_subscription_plan_version_price_id'), 'subscription', ['plan_version_price_id'], unique=False)
    op.create_index(op.f('ix_subscription_provider_subscription_id'), 'subscription', ['provider_subscription_id'], unique=True)
    op.create_table('subscription_discount',
    sa.Column('subscription_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('discount_id', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False, comment='Value as granted, frozen at that moment'),
    sa.Column('unit_id', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['discount_id'], ['license_discount.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['license_discount_unit.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', name='uq_subscription_discount_subscription')
    )
    op.create_index(op.f('ix_subscription_discount_discount_id'), 'subscription_discount', ['discount_id'], unique=False)
    op.create_index(op.f('ix_subscription_discount_subscription_id'), 'subscription_discount', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_subscription_discount_unit_id'), 'subscription_discount', ['unit_id'], unique=False)
    op.create_table('subscription_user',
    sa.Column('subscription_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_user')
    op.drop_index(op.f('ix_subscription_discount_unit_id'), table_name='subscription_discount')
    op.drop_index(op.f('ix_subscription_discount_subscription_id'), table_name='subscription_discount')
    op.drop_index(op.f('ix_subscription_discount_discount_id'), table_name='subscription_discount')
    op.drop_table('subscription_discount')
    op.drop_index(op.f('ix_subscription_provider_subscription_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_plan_version_price_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_plan_version_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_commitment_end_date'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_client_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_billing_mode_id'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_index(op.f('ix_license_plan_version_rule_rule_id'), table_name='license_plan_version_rule')
    op.drop_index(op.f('ix_license_plan_version_rule_plan_version_id'), table_name='license_plan_version_rule')
    op.drop_table('license_plan_version_rule')
    op.drop_index(op.f('ix_license_plan_version_price_plan_version_id'), table_name='license_plan_version_price')
    op.drop_index(op.f('ix_license_plan_version_price_period_id'), table_name='license_plan_version_price')
    op.drop_index(op.f('ix_license_plan_version_price_currency_id'), table_name='license_plan_version_price')
    op.drop_index(op.f('ix_license_plan_version_price_commitment_id'), table_name='license_plan_version_price')
    op.drop_table('license_plan_version_price')
    op.drop_index(op.f('ix_license_plan_version_plan_id'), table_name='license_plan_version')
    op.drop_table('license_plan_version')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_batch_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_license_plan_client_id'), table_name='license_plan')
    op.drop_index(op.f('ix_license_plan_app_id'), table_name='license_plan')
    op.drop_table('license_plan')
    op.drop_index('ix_client_request_user', table_name='client_request')
    op.drop_index('ix_client_request_status_type', table_name='client_request')
    op.drop_index('ix_client_request_processed', table_name='client_request')
    op.drop_index('ix_client_request_client_status', table_name='client_request')
    op.drop_table('client_request')
    op.drop_table('webservice_access_level')
    op.drop_table('user_sso_link')
    op.drop_table('user_role')
    op.drop_table('user_refresh_token')
    op.drop_table('user_private_data')
    op.drop_table('user_one_time_token')
    op.drop_table('user_login_attempt')
    op.drop_index(op.f('ix_user_event_preference_user_id'), table_name='user_event_preference')
    op.drop_index(op.f('ix_user_event_preference_event_type'), table_name='user_event_preference')
    op.drop_table('user_event_preference')
    op.drop_table('user_emailing')
    op.drop_table('user_email_address')
    op.drop_table('user_audit_log')
    op.drop_table('notification_type_role')
    op.drop_index(op.f('ix_notification_batch_type_id'), table_name='notification_batch')
    op.drop_index(op.f('ix_notification_batch_triggered_by_user_id'), table_name='notification_batch')
    op.drop_table('notification_batch')
    op.drop_table('migration_job_execution')
    op.drop_index('ix_legal_acceptance_version', table_name='legal_document_acceptance')
    op.drop_index('ix_legal_acceptance_user', table_name='legal_document_acceptance')
    op.drop_index('ix_legal_acceptance_retention', table_name='legal_document_acceptance')
    op.drop_index('ix_legal_acceptance_email', table_name='legal_document_acceptance')
    op.drop_table('legal_document_acceptance')
    op.drop_table('file_import')
    op.drop_table('cron_job_execution')
    op.drop_table('client_user_role')
    op.drop_index(op.f('ix_client_provider_customer_id'), table_name='client')
    op.drop_table('client')
    op.drop_index(op.f('ix_ai_message_feedback_user_id'), table_name='ai_message_feedback')
    op.drop_index(op.f('ix_ai_message_feedback_message_id'), table_name='ai_message_feedback')
    op.drop_table('ai_message_feedback')
    op.drop_index(op.f('ix_ai_conversation_summary_through_message_id'), table_name='ai_conversation_summary')
    op.drop_index(op.f('ix_ai_conversation_summary_conversation_id'), table_name='ai_conversation_summary')
    op.drop_table('ai_conversation_summary')
    op.drop_table('webservice')
    op.drop_table('user')
    op.drop_index('ix_stored_file_client_content_hash', table_name='stored_file')
    op.drop_table('stored_file')
    op.drop_index(op.f('ix_role_webservice_role_id'), table_name='role_webservice')
    op.drop_table('role_webservice')
    op.drop_index(op.f('ix_notification_type_severity_id'), table_name='notification_type')
    op.drop_table('notification_type')
    op.drop_index(op.f('ix_license_discount_unit_id'), table_name='license_discount')
    op.drop_index(op.f('ix_license_discount_grant_id'), table_name='license_discount')
    op.drop_table('license_discount')
    op.drop_index('ix_legal_version_current', table_name='legal_document_version')
    op.drop_table('legal_document_version')
    op.drop_table('job')
    op.drop_table('emailing_type_role')
    op.drop_table('emailing')
    op.drop_index(op.f('ix_ai_message_conversation_id'), table_name='ai_message')
    op.drop_table('ai_message')
    op.drop_table('webservice_public_type')
    op.drop_table('user_status')
    op.drop_table('user_audit_log_type')
    op.drop_table('stored_file_type')
    op.drop_table('role')
    op.drop_table('one_time_token_type')
    op.drop_table('one_time_token_status')
    op.drop_table('notification_severity')
    op.drop_table('login_attempt_status')
    op.drop_table('log')
    op.drop_table('license_rule')
    op.drop_table('license_price_period')
    op.drop_table('license_discount_unit')
    op.drop_table('license_discount_grant')
    op.drop_table('license_currency')
    op.drop_table('license_commitment')
    op.drop_table('license_billing_mode')
    op.drop_table('license_application')
    op.drop_table('legal_document_type')
    op.drop_table('language')
    op.drop_table('job_status')
    op.drop_table('gender')
    op.drop_table('file_import_type')
    op.drop_table('file_import_status')
    op.drop_table('emailing_type')
    op.drop_table('emailing_status')
    op.drop_table('client_request_type')
    op.drop_table('client_request_status')
    op.drop_index(op.f('ix_ai_conversation_user_id'), table_name='ai_conversation')
    op.drop_index(op.f('ix_ai_conversation_purpose'), table_name='ai_conversation')
    op.drop_index(op.f('ix_ai_conversation_client_id'), table_name='ai_conversation')
    op.drop_table('ai_conversation')
    op.drop_table('access_level')
    # ### end Alembic commands ###
